/**
 * WorkTrain Inbox Command
 *
 * Reads unread messages from ~/.workrail/outbox.jsonl and marks them as read.
 * The daemon appends to outbox.jsonl to notify the user (completions, questions,
 * findings that need human judgment).
 *
 * Design invariants:
 * - All I/O is injected via WorktrainInboxCommandDeps. Zero direct fs/os imports.
 * - outbox.jsonl is NEVER modified by this command (append-only for the daemon).
 * - Read state is tracked in ~/.workrail/inbox-cursor.json as {lastReadCount: number}.
 * - If the cursor is missing or corrupted, it defaults to 0 (show all messages).
 * - If cursor > totalLines (outbox was truncated or wiped), cursor resets to 0.
 *   (cursor === totalLines means "all messages read" -- normal state, no reset.)
 * - Malformed JSON lines are skipped with a warning, not a crash.
 * - --watch is accepted but prints a stub message (daemon coordinator not built yet).
 * - All failures are returned as CliResult failure variants -- never thrown.
 */

import type { CliResult } from '../types/cli-result.js';
import { success, failure } from '../types/cli-result.js';

// ═══════════════════════════════════════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════════════════════════════════════

/**
 * A single entry in outbox.jsonl.
 * Written by the daemon; read by this command.
 */
export interface OutboxMessage {
  /** UUIDv4 generated by the daemon. */
  readonly id: string;
  /** The notification text from the daemon. */
  readonly message: string;
  /** ISO 8601 timestamp of when the daemon enqueued this notification. */
  readonly timestamp: string;
}

/**
 * Persisted cursor state for the inbox command.
 * Stored in ~/.workrail/inbox-cursor.json.
 */
export interface InboxCursor {
  /** Number of valid parsed messages in outbox.jsonl that have been shown to the user. */
  readonly lastReadCount: number;
}

/**
 * All I/O operations required by the inbox command.
 * Inject real implementations in the composition root; inject fakes in tests.
 */
export interface WorktrainInboxCommandDeps {
  /** Read file contents as UTF-8 string. Throws on ENOENT. */
  readonly readFile: (path: string) => Promise<string>;
  /** Write UTF-8 string to file, creating parent directory first. */
  readonly writeFile: (path: string, content: string) => Promise<void>;
  /** Create a directory (recursive: true = mkdir -p). */
  readonly mkdir: (path: string, options: { recursive: boolean }) => Promise<string | undefined>;
  /** Return the user's home directory. */
  readonly homedir: () => string;
  /** Join path segments (same semantics as node:path join). */
  readonly joinPath: (...paths: string[]) => string;
  /** Print a line to stdout. */
  readonly print: (line: string) => void;
  /**
   * Sleep for the given number of milliseconds.
   * Used by --watch to poll at a fixed interval.
   * Injected so tests can override to a no-op.
   */
  readonly sleep?: (ms: number) => Promise<void>;
}

/**
 * Options for the inbox command.
 */
export interface WorktrainInboxCommandOpts {
  /**
   * When true, watch for new outbox messages in real time.
   * NOT YET IMPLEMENTED -- prints a stub message and exits cleanly.
   * Requires the daemon coordinator loop (not yet built).
   */
  readonly watch?: boolean;
}

// ═══════════════════════════════════════════════════════════════════════════
// COMMAND EXECUTION
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Execute the `worktrain inbox` command.
 *
 * Reads unread messages from ~/.workrail/outbox.jsonl, prints them to stdout,
 * and advances the cursor in ~/.workrail/inbox-cursor.json.
 *
 * Returns CliResult success in all normal cases (including empty inbox).
 * Returns CliResult failure only on unexpected I/O errors.
 */
export async function executeWorktrainInboxCommand(
  deps: WorktrainInboxCommandDeps,
  opts: WorktrainInboxCommandOpts = {},
): Promise<CliResult> {
  const workrailDir = deps.joinPath(deps.homedir(), '.workrail');
  const outboxPath = deps.joinPath(workrailDir, 'outbox.jsonl');
  const cursorPath = deps.joinPath(workrailDir, 'inbox-cursor.json');

  if (opts.watch) {
    // Poll every 2 seconds. Print new messages and update cursor on each cycle.
    // Exits cleanly on SIGINT (Ctrl-C) -- the process.on('SIGINT') handler lets
    // the current poll complete, then the while-loop exits on the next check.
    deps.print('Watching for new messages (Ctrl-C to stop)...');
    const sleepFn = deps.sleep ?? ((ms: number) => new Promise<void>((resolve) => setTimeout(resolve, ms)));
    let running = true;
    const onSigint = () => { running = false; };
    process.once('SIGINT', onSigint);

    while (running) {
      await readAndPrint(deps, outboxPath, cursorPath, workrailDir, true);
      if (!running) break;
      await sleepFn(2000);
    }

    process.removeListener('SIGINT', onSigint);
    deps.print('');
    deps.print('Stopped watching.');
    return success({ message: 'Watch stopped.' });
  }

  const result = await readAndPrint(deps, outboxPath, cursorPath, workrailDir);
  return result;
}

/**
 * Read outbox, print unread messages, and update cursor.
 * Shared by both single-run and --watch polling paths.
 *
 * @param silentOnEmpty - When true (watch mode), suppress "No new messages." to
 *   avoid printing it every 2 seconds when nothing is happening.
 */
async function readAndPrint(
  deps: WorktrainInboxCommandDeps,
  outboxPath: string,
  cursorPath: string,
  workrailDir: string,
  silentOnEmpty = false,
): Promise<CliResult> {
  // ── Read outbox ──────────────────────────────────────────────────────────

  let outboxContent: string;
  try {
    outboxContent = await deps.readFile(outboxPath);
  } catch (err) {
    // ENOENT = outbox doesn't exist yet = no messages
    if (isEnoent(err)) {
      deps.print('No messages.');
      return success({ message: 'No messages.' });
    }
    return failure(
      `Failed to read outbox: ${err instanceof Error ? err.message : String(err)}`,
    );
  }

  // Parse outbox lines, skipping malformed entries
  const allLines = outboxContent.split('\n').filter((line) => line.trim() !== '');
  const parsed: OutboxMessage[] = [];
  let malformedCount = 0;

  for (const line of allLines) {
    try {
      const msg = JSON.parse(line) as OutboxMessage;
      parsed.push(msg);
    } catch {
      malformedCount++;
    }
  }

  const totalLines = parsed.length;

  // ── Read cursor ──────────────────────────────────────────────────────────

  let lastReadCount = 0;
  try {
    const cursorContent = await deps.readFile(cursorPath);
    const cursor = JSON.parse(cursorContent) as InboxCursor;
    if (typeof cursor.lastReadCount === 'number' && cursor.lastReadCount >= 0) {
      lastReadCount = cursor.lastReadCount;
    }
  } catch {
    // Missing cursor file or corrupted JSON -- default to 0 (show all)
    lastReadCount = 0;
  }

  // Cursor desync guard: if outbox was truncated/wiped, the cursor may point
  // past the end of the file. Reset it so the user sees all current messages.
  // Only fires when cursor STRICTLY exceeds total lines (not when equal, which
  // is the normal "all messages read" state).
  if (lastReadCount > totalLines) {
    lastReadCount = 0;
  }

  // ── Show unread messages ─────────────────────────────────────────────────

  const unread = parsed.slice(lastReadCount);
  const newCount = unread.length;

  if (malformedCount > 0) {
    deps.print(`Warning: skipped ${malformedCount} malformed line(s) in outbox.jsonl.`);
  }

  if (newCount > 0) {
    for (const msg of unread) {
      deps.print(`[${msg.timestamp}] ${msg.message}`);
    }
    deps.print('');
    deps.print(`${newCount} new message(s).`);
  }

  // ── Write updated cursor ─────────────────────────────────────────────────

  const newCursor: InboxCursor = { lastReadCount: totalLines };

  try {
    await deps.mkdir(workrailDir, { recursive: true });
    await deps.writeFile(cursorPath, JSON.stringify(newCursor, null, 2) + '\n');
  } catch (err) {
    // Cursor write failure is non-fatal -- messages were already shown.
    // Warn but return success so the user doesn't think inbox failed.
    deps.print(
      `Warning: could not update read cursor: ${err instanceof Error ? err.message : String(err)}`,
    );
  }

  if (newCount === 0 && !silentOnEmpty) {
    deps.print('No new messages.');
  }

  return success({ message: `${newCount} new message(s).` });
}

// ═══════════════════════════════════════════════════════════════════════════
// HELPERS
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Returns true if the error is a Node.js ENOENT (file not found).
 */
function isEnoent(err: unknown): boolean {
  return (
    err !== null &&
    typeof err === 'object' &&
    'code' in err &&
    (err as { code: unknown }).code === 'ENOENT'
  );
}
